
STATUS_SUCCESS = "SUCCESS"
STATUS_OK = "OK"
STATUS_FAIL = "FAIL"

MSG_INVLID_TOKEN = 'MSG_INVLID_TOKEN'
MSG_TOEKN_EXPIRED = 'MSG_TOEKN_EXPIRED'
MSG_MISSING_USER_PASSWORD = 'MSG_MISSING_USER_PASSWORD'
MSG_ACCESS_DENIED = 'MSG_ACCESS_DENIED'
MSG_ACCESS_RIGHTS_ERROR = 'MSG_ACCESS_RIGHTS_ERROR'
MSG_LOGIN_FAILED = 'MSG_LOGIN_FAILED'
MSG_SERVER_ERROR = 'MSG_SERVER_ERROR'